### PR TITLE
Update team data

### PR DESCRIPTION
**Pull request by rylev**
Fixing an issue discovered in https://github.com/rust-lang/team/pull/1414

### CODE REVIEW

**Comment by Kobzol** [comment]
Could you please apply this? https://github.com/rust-lang/sync-team/pull/75/commits/55e1df4f583ff47efcd23345779b74aa1fc8ec37 (and return `None` for RenovateBot). We shouldn't treat the renovate bot as a github account.

**Comment by rylev** [comment]
@Kobzol done!

**Review by Kobzol — APPROVED** [review]
LGTM.

**Comment by Kobzol** [comment]
I will try to add a test that actually fetches the team API from its production URL.

**Comment by rylev** [comment]
Closing in favor of https://github.com/rust-lang/sync-team/pull/75

**Pull request closed without merging**
